import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import ScrollToTop from "@/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Infinity Space",
  description: "Generated by create next app",
  verification: {
    google: "sDT_C1rSvwbbIdaL0aU0Vv9ChKIUiArSabp3vAUXw9Q",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-GFEHPG6X0T"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-GFEHPG6X0T');
          `}
        </Script>

        <ScrollToTop />
        <Navbar />

        <main className="flex-1 pt-[70px] sm:pt-[75px] lg:pt-[100px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
